### ISSUE TITLE
[Request for making docs more readable]: Remove Git Messages

### ISSUE THREAD

**Issue by aerocyber** [kivy/kivy-website-docs#7]
There are some pages with git messages like this one: [https://kivy.org/doc/stable/installation/installation-linux.html#linux-ppa](https://kivy.org/doc/stable/installation/installation-linux.html#linux-ppa) that makes it less readable. I would like to request the dev team to look into this.
Thank you

**Comment by tshirtman** [comment]
Thanks for reporting, actually this was fixed recently in source, but seems the doc didn't build automatically since, we'll have to investigate that.

**Comment by aerocyber** [comment]
You are welcome!
And thanks for the immediate response, @tshirtman .So, should I leave it open or close it, since it was the build system and not the docs?

**Comment by tshirtman** [comment]
I think we can leave it open until it's fixed.

**Comment by tshirtman** [comment]
finally found the time to fix it!

**Comment by aerocyber** [comment]
Thanks for looking into it @tshirtman .
And, I have confirmed the fix to be working.
