### ISSUE TITLE
doc search results contain incorrect link.

### ISSUE THREAD

**Issue by dawnfantasy** [kivy/kivy-website-docs#8]
https://kivy.org/doc/stable/search.html?q=wind

The result link "https://kivy.org/doc/stable/api-kivy.core.windowundefined?highlight=wind" is incorrect.
It should be     "https://kivy.org/doc/stable/api-kivy.core.window.html?highlight=wind", substituting 'undefined' with '.html'.

Thank you.

**Comment by misl6** [comment]
Duplicated of https://github.com/kivy/kivy/issues/7697
